# Generated by Django 2.2.7 on 2019-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theknot', '0002_auto_20191114_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending_reception',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending_wedding',
            field=models.BooleanField(default=True),
        ),
    ]
