# Generated by Django 2.2.7 on 2019-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theknot', '0004_auto_20191114_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
