# Generated by Django 2.2.7 on 2019-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=15)),
                ('last_name', models.TextField(default='', max_length=15)),
                ('message', models.TextField(max_length=60)),
                ('email', models.EmailField(max_length=15, unique=True)),
                ('attending_wedding', models.BooleanField(default=False)),
                ('attending_reception', models.BooleanField(default=False)),
                ('additional_guests', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(default='')),
                ('submission_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
