# Generated by Django 2.2.7 on 2019-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theknot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending_reception',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending_wedding',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
